### ISSUE TITLE
all.css needs to be cleaned up

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/cgxp#272]
The following doesn't seem to be needed or shouldn't be in CGXP:

``` css
div#header-out {
    position: relative;
    z-index: 20001;
}
.app-accordion-body {
    padding: 3px;
}
.x-toolbar .maxExtent {
    background: url('img/map_magnify.png') top left no-repeat;
}
.x-toolbar .mapZoomIn {
    background: url('img/zoom_in.png') top left no-repeat;
}
.x-toolbar .mapZoomOut {
    background: url('img/zoom_out.png') top left no-repeat;
}
.x-toolbar .mapHistoryPrevious {
    background: url('img/arrow_left.png') top left no-repeat;
}
.x-toolbar .mapHistoryNext {
    background: url('img/arrow_right.png') top left no-repeat;
}
```
